/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/validator`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/auth/callback/route`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/api`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSession`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/code` | `/code`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/classement` | `/classement`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/banque` | `/banque`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/.next/types/app/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/.next/types/app/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/.next/types/validator`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/.next/types/app/auth/callback/route`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/.next/types/app/dashboard/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/api`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useSession`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/code` | `/code`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/classement` | `/classement`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/banque` | `/banque`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../../web/.next/types/app/layout${`?${string}` | `#${string}` | ''}` | `/../../web/.next/types/app/page${`?${string}` | `#${string}` | ''}` | `/../../web/.next/types/validator${`?${string}` | `#${string}` | ''}` | `/../../web/.next/types/app/auth/callback/route${`?${string}` | `#${string}` | ''}` | `/../../web/.next/types/app/dashboard/page${`?${string}` | `#${string}` | ''}` | `/../lib/api${`?${string}` | `#${string}` | ''}` | `/../hooks/useSession${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/code${`?${string}` | `#${string}` | ''}` | `/code${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/classement${`?${string}` | `#${string}` | ''}` | `/classement${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/banque${`?${string}` | `#${string}` | ''}` | `/banque${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/validator`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/auth/callback/route`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/app/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/api`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSession`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/code` | `/code`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/classement` | `/classement`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/banque` | `/banque`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
